### PR TITLE
Minor tweaks within code

### PR DESCRIPTION
**Pull request by IamRENCE**
### Summary:
- Refactored some methods
- Fixed minor typo errors
- Tweaked functionality of AddressBook, where case does not matter in emails

### CODE REVIEW

**Comment by damithc** [comment]
@IamRENCE it is enough to push your commits to your own fork. No need to create a PR.

**Comment by IamRENCE** [comment]
Hello Prof,

Can I check if my account is linked to my NUS NetID e0175937? I did the pre-module survey and I hope to confirm that it is linked.

Thanks!

Cheers,
Terence



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by damithc** [comment]
We are fixing some loopholes in the script. Please ping me again if you didn't receive the correct response for the AB1 enhancement by the end of this week.

**Comment by damithc** [comment]
> Can I check if my account is linked to my NUS NetID e0175937? I did the pre-module survey and I hope to confirm that it is linked.

Sorry, I missed this query. Did you get marks for it?

**Comment by IamRENCE** [comment]
Hello Prof,

Yes, I did after a few days later. Sorry for the inconvenience!
Thanks.

Cheers,
Terence

**Pull request closed without merging**
